					<h3>The whales are still thick from Santa Cruz to Monterey</h3>
					<p><img src="/images/246.jpg" alt="Whales are thick while Whale Watching in Monterey Bay California with Stagnaro Charters"></p>
					<p>Monday, November 3, 2014: On Saturday the much-needed rain cleared out so we headed out whale watching! We had lots of humpback whales close to home, only 5 miles out of Santa Cruz! We watched a group of 8 humpbacks surface feeding with a herd of about 200 California sea lions. The feeding pack came right by the boat several times. There were another 6-10 whales also in the area around us. Then we came upon a pod of over 300 common dolphins that swam along with the moving boat for about 20 minutes!</p>
					<p>Sunday we had lots of whales that were more spread out through the Monterey Bay. But we saw multiple breaching and tail throwing and all kinds of spectacular surface behaviors this day.</p>
					<p>A special treat – We saw a <a href="https://en.wikipedia.org/wiki/Steller_sea_lion" title="Steller Sea Lion" target="_blank">Steller Sea Lion</a> on the mile buoy last week, these guys are massive!</p>
					<img src="/images/247.jpg" alt="xxxxxxxxxxx while Whale Watching in Monterey Bay California with Stagnaro Charters">
					<p class="cr">Steller Sea Lion, Monterey Bay near Santa Cruz. Photo: Michael Nelson</p>
					<p>The next Santa Cruz Whale Watching trip is scheduled for Wednesday, November 5 at 12:00 PM. Flat calm conditions are expected, with the humpback whales and dolphins still actively feeding and frolicking in the Monterey Bay! Our fully-narrated 3-4 hour whale watching trip leaves from The Santa Cruz Yacht Harbor. Trips do go rain or shine!</p>
					<p>Look! We had an awesome visit from some friendly humpback whales on Friday, October 18!</p>
					<iframe src="https://www.youtube.com/embed/hvxo8yYmE5w" frameborder="0" allowfullscreen></iframe>
					<p>Here are some neat <a href="http://www.santacruzsentinel.com/general-news/20141030/whales-dolphins-spotted-near-moss-landing" title="aerial photos" target="_blank">aerial photos</a> of humpback whales and sea lions near Moss Landing last week.</p>
					<p>Orange County – Our neighbors down south have had some amazing and rare sightings over the last month – <a href="http://www.today.com/news/rare-pilot-whales-seen-coast-southern-california-1D80227619" title="pilot whales and sperm whales spotted off of Dana Point!" target="_blank">pilot whales and sperm whales spotted off of Dana Point!</a> If you are down in the southland get out there! Try <a href="http://www.dolphinsafari.com/" title="Captain Dave's Dolphin Safari" target="_blank">Captain Dave's Dolphin Safari</a> or <a href="http://ococeanadventures.com/" title="Dana Wharf Whale Watching" target="_blank">Dana Wharf Whale Watching</a>.</p>
					<p>Monterey Bay W.E.T. Rescue Crew, Thank you for your great work! Here's a big shout out to rescuers from the Whale Entanglement Team this week for helping out a <a href="http://www.montereyherald.com/20141101/rescuers-free-entangled-whale-near-point-pinos" title="juvenile humpback whale who got its tail caught up in buoy line" target="_blank">juvenile humpback whale who got its tail caught up in buoy line</a>. For more information on how you can support the Monterey Bay W.E.T. volunteer crew, visit the <a href="https://www.facebook.com/MontereyBayMarineLifeStudies" title="Monterey Bay Marine Life Studies Facebook page" target="_blank">Monterey Bay Marine Life Studies Facebook page</a>.</p>
					<p class="cr">This entry was posted on November 3, 2014 by jennyo.</p>
					<p class="book">Book your trip today! <a @include('linkhref')>Book online now</a> or call <em>(831) 427-0230</em></p>
					<hr>
