					<h1>Dan Haifley, Our Ocean Backyard: Gray whale time</h1>
					<p><img src="/images/dan.jpg" alt="Dan Haifley while Whale Watching in Monterey Bay California with Stagnaro Charters"></p>
					<h2>By Dan Haifley</h2>
					<p>Special to the Sentinel</p>
					<p>POSTED:   01/03/2014 03:53:13 PM PST</p>
					<p>The year 2013 saw an unusually busy humpback whale season on Monterey Bay, driven by the upwelling of nutrient-laden waters feeding plankton, krill, anchovies and other small fish which attracted them.</p>
					<p>While there are still humpbacks in the bay, California gray whales have begun their twice-a-year glide through Central Coast waters as they first head south to where they rest, breed and give birth in warmer Mexico, then return north to their feeding grounds off Alaska.</p>
					<p>Gray whales were first spotted migrating through Monterey Bay in December. They’re best observed from a boat run by an experienced whale watching captain and crew. Ken Stagnaro, who owns the Velocity that takes guided whale tours out of the Santa Cruz Harbor, says that while humpbacks are more animated when they visit the Monterey Bay to feed, the grays use the central coast as a thoroughfare and stay focused on their long trek. But their speed and force is constant, said Stagnaro, so finding and following them is easier. “They are very majestic to watch, especially when they breech,” he says.</p>
					<p>Their southern destinations are balmy Baja California waters where females can mate, give birth, then nurse and nurture their young at spots including Laguna San Ignacio, Laguna Guerrero Negro, Laguna Ojo de Liebre and Magdalena Bay. Mating can also happen during their southern migration. While they can sometimes be friendly to humans in Baja California, they’re not as approachable during mating and birthing.</p>
					<p>Their gestation period is about a year after which calves are born live, most at around 15 feet in length and weighing 1,500 pounds. They put on weight and grow as they nurse on mother’s milk, more than half of which is fat. They can ultimately grow up to 50 feet, weigh as much as 40 tons and live 80 years. Their population is believed to be as high as 22,000, up from previous years.</p>
					<p>Around the middle of February, they head north to Alaska for their summer feeding, primarily on a small crustacean called “amphipod macrocephela” which is nourished by algae that drops from sea ice in the Bering and Chukchi seas. They’ll also eat smaller amphipods, which can look like a type of shrimp under a microscope. If they do need to eat during their migration they’ll forage in the sea floor’s mud, sand and silt.</p>
					<p>The best period for viewing the northward migration is February through May. This portion of their journey is more social and leisurely than the southbound trip. Mothers and calves can be spotted in April and May, and sometimes they travel close enough to shore that they can be seen from high points along the coast.</p>
					<p>Their coastal highway gets busy as the southern and northern migrations coincide during February, although the southbound whales travel further offshore than the northbound ones do. They travel from 38 degree waters to those that are a balmier 70 degrees. When they leave Alaska they can have up to 8 inches of blubber to sustain them on journey and when they return they have just 2 to 3 inches left. Mothers need more, said Stagnaro, to nurse their young on the trip north.</p>
					<p>You can see them as they perform their annual ritual — now as they head south, and later if you want to see them head north.</p>
					<p>Dan Haifley is executive director of O’Neill Sea Odyssey.</p>
					<p class="credit"><a href="xxxxxxxx" title="">Santa Cruz Sentinel</a></p>
					<p class="credit">This entry was posted in Press Coverage and tagged gray whale, gray whales, monterey california whale watching, monterey whale watching, santa cruz, santa cruz whale watching, stagnaro on January 7, 2014 by jennyo</p>
					<hr>
					